config/routes.rb
Hyperbolic::Application.routes.draw do

  resources :posts
  resources :users, :only => [:new, :create]
  resources :admin_toolbars, :only => [:show]
  root :to => 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :published, :published_at, :title, :abstract

  validate :permalink_uniqueness

  before_create :generate_permalink

  scope :published, where(:published => true).order("published_at DESC")
  
  def generate_permalink
    self.permalink = self.title.parameterize unless self.permalink.present?
  end

  def permalink_uniqueness
    if Post.find_by_permalink(self.title.parameterize)
      errors[:base] << "This title has been already used, please change it." unless permalink
    end
  end

  def to_param
    self.permalink
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
end

app/controllers/admin_toolbars_controller.rb
class AdminToolbarsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Authentication
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  caches_page :index, :show
  cache_sweeper :post_sweeper

  before_filter :authorize, :except => [:index, :show]
  before_filter(only: [:index, :show]) { @page_caching = true }

  def index
    if current_user
      @posts = Post.order("published_at DESC")
    else 
      @posts = Post.published
    end
  end

  def show
    if current_user
      @post = Post.find_by_permalink(params[:id])
    else 
      @post = Post.published.find_by_permalink(params[:id])
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post])
    if @post.save
      redirect_to posts_url
    else
      render :new
    end
  end

  def edit
    @post = Post.find_by_permalink(params[:id])
  end

  def update
    @post = Post.find_by_permalink(params[:id])
    if @post.update_attributes(params[:post])
      redirect_to posts_url
    else
      render :edit
    end
  end

  def destroy

  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  def new
    if User.all.size < 1
      super
    else
      redirect_to root_url
    end
  end

  def create
    if User.all.size < 1
      super
      redirect_to root_url
    end
  end

end

app/helpers/admin_toolbars_helper.rb
module AdminToolbarsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hyperbolic Motion</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags unless @page_caching %>
  
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-35488114-1']);
    _gaq.push(['_setDomainName', 'hyperbolicmotion.com']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
  
</head>
<body>
    <div id ="admin">
        <% if @post and !@post.new_record? %>
         <%= link_to "Edit", edit_post_path(@post) %>  |   
       <% end %>
        <%= link_to "New", new_post_path %>  |  
        <%= link_to "Sign out", session_path, method: :delete %>
    </div>
    <section>
      <%= yield %> 
    </section>
    <footer>
      template forked from <a href="https://github.com/cloudhead/dorothy">Dorothy</a>
    </footer>        
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post, :html => {:class => 'form-horizontal' }) do |form| %>
  <% if @post.errors[:base].any? %>
    <ul>
    <% @post.errors[:base].each do |error| %>
      <li><%= error %></li>
    <% end %>
    </ul>
  <% end %>
  <%= form.input :title %>
  <%= form.input :published %>
  <%= form.input :body %>
  <%= form.input :abstract %>
  <%= form.input :published_at %>
  <%= form.button :submit %>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Hyperbolic Motion</h1>
<ul>
  <% if @posts.length > 0 %>
    <% for post in @posts %>
      <li>
        <%= post.published_at %> &raquo; <%= link_to post.title, post_url(post) %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<article class="post">
  <header>
    <h1><%= @post.title %></h1>
    <span class="date"><%= @post.published_at.strftime("%e %B %Y") %></span>
  </header>

  <section class="content">
    <%= raw RDiscount.new(@post.body).to_html %>
  </section>


  <section class="comments">
      <div id="disqus_thread"></div>
      <script type="text/javascript" src="http://disqus.com/forums/hyperbolicmotion/embed.js"> </script>
      <noscript><a href="http://hyperbolicmotion.disqus.com/?url=ref">View the discussion thread.</a></noscript>
      <a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
  </section>
</article>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/users/_form.html.erb
<div class='text_field'>
  <%= form.label :email %>
  <%= form.text_field :email, :type => 'email' %>
</div>

<div class='password_field'>
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<h2>Sign up</h2>

<%= form_for @user do |form| %>
  <%= render :partial => '/users/form', :object => form %>
  <%= form.submit 'Sign up' %>
<% end %>

app/views/users/show.js.erb
<% if current_user %>
  $('#admin').show();
<% end %>